# Connect to Postgres via the shared transaction-mode pooler (IPv4-only)
DATABASE_URL="postgresql://postgres.prqehyjcaodmkwwuhkna:1ng3n13r1A%40%40%C2%B7@aws-0-us-east-2.pooler.supabase.com:6543/postgres"

# Connect to Postgres via the shared session-mode pooler (used for migrations)
DIRECT_URL="postgresql://postgres.prqehyjcaodmkwwuhkna:1ng3n13r1A%40%40%C2%B7@aws-0-us-east-2.pooler.supabase.com:5432/postgres"